spring:
  application:
    name: product-management-api
  main:
    banner-mode: console
  datasource:
    url: jdbc:postgresql://localhost:5432/product_management
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
