# spring:
#   application:
#     name: product-management-api
#   main:
#     banner-mode: off
#   datasource:
#     url: jdbc:postgresql://localhost:5432/product_management
#     username: postgres
#     password: 1234
#     driver-class-name: org.postgresql.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

server:
  port: ${PORT:8080}
spring:
  application:
    name: product-management-api
  main:
    banner-mode: console
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/product_management}
    url: ${DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres.railway.internal:5432/railway}}
    #    username: ${PGUSER:postgres}
    username: ${PGUSER:${SPRING_DATASOURCE_USERNAME:postgres}}
    #    password: ${PGPASSWORD:1234}
    password: ${PGPASSWORD:${SPRING_DATASOURCE_PASSWORD:TsZtqvpXfUdlgCMVHTXafPLKHHwknwci}}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
    enabled: true